name: Publish to Zed

on:
  create:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
    steps:
      - name: Debug info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.ref_type }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Tag: ${GITHUB_REF#refs/tags/}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: catppuccin-blur
          push-to: jenslys/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
