name: Publish to Zed

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: catppuccin-blur
          push-to: jenslys/extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
