name: Sync Theme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [catppuccin-update]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync theme
        run: python sync_theme.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "feat: sync with latest Catppuccin theme"
          title: "feat: sync with latest Catppuccin theme"
          body: |
            Automated theme sync with latest Catppuccin theme.

            - Synced with latest Catppuccin theme
            - Applied blur customizations
            - Updated all variants including Espresso
          branch: feat/theme-sync
          delete-branch: true
          labels: |
            theme
            automated pr
